name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: |
          pnpm install
      - name: Test
        run: |
          pnpm run test
      - name: Create Release
        run: |
          pnpm auto shipit
