name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install
        run: |
          pnpm install
      - name: Test
        run: |
          pnpm run test
      - name: Create Release
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm auto shipit
